services:
  receiver:
    url: http://receiver:8080/receiver/health
  storage:
    url: http://storage:8090/storage/health
  processing:
    url: http://processing:8100/processing/health
  analyzer:
    url: http://analyzer:8110/analyzer/health

scheduler:
  period: 20

datastore:
  filename: /data/health/health_stats.json
