openapi: 3.0.0
info:
  description: This API provides event stats
  version: "1.0.0"
  title: Stats API
  contact:
    email: tchau29@my.bcit.ca
paths:
  /stats:
    get:
      summary: Gets the event stats
      operationId: app.get_stats
      description: Gets train statistics
      responses:
        '200':
          description: Successfully returned a stats object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadingStats'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Statistics do not exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    ReadingStats:
      required:
      - num_wait_time_readings
      - num_passengers_readings
      - max_passengers
      - min_wait_time
      properties:
        num_wait_time_readings:
          type: integer
          example: 12345
        num_passengers_readings:
          type: integer
          example: 67890
        max_passengers:
          type: integer
          example: 120
        min_wait_time:
          type: integer
          example: 1
      type: object
