version: 1
scheduler:
  interval: 5

events:
  passenger_count:
    url: http://storage:8090/storage/na_train/passenger_count
  wait_time:
    url: http://storage:8090/storage/na_train/incoming_train

data_store:
  filename: /data/processing/processing.json
